/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rhythmgame;

import java.awt.Color;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author lcros3
 */
public class Summary extends javax.swing.JFrame implements ActionListener {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Summary.class.getName());

    /**
     * Creates new form Summary
     */
    public Summary() {
        initComponents();
        setTitle("Summary");
        setSize(900, 900);
        setLayout(null); //removes default layout manager (box)
        Container c = getContentPane(); //instead of a JPanel; easier to set coordinates of labels, textFields and buttons
        setLocationRelativeTo(null);
        c.setBackground(new Color(40, 120, 200, 100));

        backButton.addActionListener(this);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        rank = new javax.swing.JLabel();
        numSick = new javax.swing.JLabel();
        accuracy = new javax.swing.JLabel();
        numGood = new javax.swing.JLabel();
        numBad = new javax.swing.JLabel();
        score = new javax.swing.JLabel();
        numMiss = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(900, 900, 900, 900));

        rank.setFont(new java.awt.Font("Segoe UI", 1, 80)); // NOI18N
        rank.setText("S");

        numSick.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numSick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numSick.setText("# SICK");

        accuracy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        accuracy.setText("100%");

        numGood.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numGood.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numGood.setText("# GOOD");

        numBad.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numBad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numBad.setText("# BAD");

        score.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        score.setText("SCORE");

        numMiss.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        numMiss.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numMiss.setText("# MISS");

        backButton.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        backButton.setText("<--");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(43, 43, 43)
                                                                .addComponent(accuracy, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(54, 54, 54)
                                                                .addComponent(rank)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numMiss, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numBad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numGood, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numSick, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(rank))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(score)
                                                .addGap(40, 40, 40)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(accuracy)
                                        .addComponent(numSick))
                                .addGap(18, 18, 18)
                                .addComponent(numGood)
                                .addGap(18, 18, 18)
                                .addComponent(numBad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numMiss))
                                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Summary().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel accuracy;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel numBad;
    private javax.swing.JLabel numGood;
    private javax.swing.JLabel numMiss;
    private javax.swing.JLabel numSick;
    private javax.swing.JLabel rank;
    private javax.swing.JLabel score;
    // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == backButton) {
            try {
                new SongSelection();
            } catch (IOException ex) {
                System.getLogger(Summary.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            dispose();
        }
    }
}
